### ISSUE TITLE
@群成员

### ISSUE THREAD

**Issue by CL545740896** [cqmoe/python-aiocqhttp#12]
你好，请问怎样可以在处理新成员入群的时候，@新入群的成员

**Comment by kj415j45** [comment]
@CL545740896 https://cqhttp.cc/docs/4.7/#/Post?id=%E7%BE%A4%E6%88%90%E5%91%98%E5%A2%9E%E5%8A%A0

**Comment by stdrc** [comment]
```py
await bot.send_group_msg(group_id=ctx['group_id'], message=f'[CQ:at,qq={ctx["user_id"]}] 欢迎～')
```

**Comment by stdrc** [comment]
[v0.6.7](https://github.com/richardchien/python-aiocqhttp/blob/master/CHANGELOG.md#v067) 中 `send()` 方法新增了 `at_sender` 参数，可以用来 at 群成员，不用手动改消息
