### ISSUE TITLE
建议修改 Quart 版本

### ISSUE THREAD

**Issue by ImSingee** [cqmoe/python-aiocqhttp#14]
根据 [Quart - Python version support](https://pgjones.gitlab.io/quart/python_versions.html) 所述，0.7.x 版本不再支持 python3.6，但是由于目前各大 Linux 系统仅仅对 Python3.6 提供了良好支持（3.7 需要源码安装），因此建议将本包 `setup.py` 文件中的 `quart>=0.6` 改为 `quart~=0.6` 。

**Comment by stdrc** [comment]
感谢提醒，已经在 master 分支修改，等下次更新的时候一并发布
