### ISSUE TITLE
set_group_click()这个api怎么调用？

### ISSUE THREAD

**Issue by needhourger** [cqmoe/python-aiocqhttp#16]
听了大佬你的建议改用这个框架了，但是现在遇到问题。
bot = CQHttp(api_root="http://127.0.0.1:5700/")
bot.set_group_kick(group_id=context['group_id'],user_id=user_id,reject_add_request=false)
群管理踢人api是这样调用吗？这样写出现RuntimeWarning,并且没有完成踢人操作
RuntimeWarning: coroutine 'UnifiedApi.call_action' was never awaited
  bot.set_group_kick(group_id=context['group_id'],user_id=user_id,reject_add_request=false)

**Comment by stdrc** [comment]
需要 `await bot.set_group_kick(...)`，这个框架用起来跟 NoneBot 一样的，只是没有命令处理的逻辑
