### ISSUE TITLE
上报类型信息的说明在哪？

### ISSUE THREAD

**Issue by benpaodewoniu** [cqmoe/python-aiocqhttp#17]
很抱歉，没有太多经验，我想知道这个 SDK 中装饰器分别对应插件的四种上报类型，且要在括号中指出类型信息。我在 API 中找不到类型信息。
比如：demo 中 
`@bot.on_notice('group_increase')`
我不知道关于类型信息的str（比如：group_increase）在哪里有说明？
还有，这个插件是否支持机器人发送图片？

**Comment by stdrc** [comment]
@benpaodewoniu https://cqhttp.cc/docs/4.8/#/Post 在这里，对应 post_type 字段

**Comment by stdrc** [comment]
@benpaodewoniu 支持，需要使用 CQ 码，同样参考上面发的 CQHTTP 插件的文档。另外，发送图片需要 酷Q Pro

**Comment by benpaodewoniu** [comment]
谢谢大佬的解答，你的这个 SDK 非常好用。
