### ISSUE TITLE
friend_add 命令无法触发？

### ISSUE THREAD

**Issue by fqb** [cqmoe/python-aiocqhttp#19]
接收不到friend_add类型的消息， 下面代码触发不了
@bot.on_notice('friend_add')
async def handle_add_new_friend(context):
     print(context)
     await bot.send(context, message='您好！', at_sender=True, auto_escape=True)
不能直接给新加入的好友发送消息，只能对方主动发消息后才能给新加好友发送消息。

**Comment by stdrc** [comment]
可以看一下 酷Q 日志里面有没有添加好友成功的日志，如果有，那 `@bot.on_notice` 会触发的
