### ISSUE TITLE
group

### ISSUE THREAD

**Issue by 13033266796** [cqmoe/python-aiocqhttp#25]
发送群聊消息发不出去，加群请求也通不过；
私聊正常，也可以通过加好友申请。

**Comment by stdrc** [comment]
看酷Q日志，通常这是因为腾讯风控

**Comment by 13033266796** [comment]
我看了酷q的日志，酷q上确实提示了发送成功；有什么办法可以解决因为风控发不出去吗？

**Comment by stdrc** [comment]
@13033266796 在同一个地方多挂一挂，然后腾讯安全管家里面能开的就开

**Comment by 13033266796** [comment]
发送群消息的日志是有的，有人申请入群的on_request还是收不到，日志里也没有写。

**Comment by stdrc** [comment]
@13033266796 你是不是开了 PC QQ

**Comment by 13033266796** [comment]
对 因为我是用自己的大号登的酷q，看酷q是登录Tim的状态，觉着不影响就把pc也登上了。

**Comment by stdrc** [comment]
@13033266796 开着PC QQ，安卓QQ就收不到加群请求了

**Comment by 13033266796** [comment]
我尝试了一下，确实是这样的。我把PC的退了，加群请求有了 也能通过请求，就是不能给群里发送消息。

**Comment by 13033266796** [comment]
我尝试了一下，确实是这样的。我把PC的退了，加群请求有了 也能通过请求，就是不能给群里发送消息。

**Comment by ExerciseBook** [comment]
@13033266796 确确实实是被风控了，如果是新QQ或者是很久没用过的号的话考虑多挂一段时间。

**Comment by 13033266796** [comment]
好的，非常感谢。
