### ISSUE TITLE
登录多个酷q

### ISSUE THREAD

**Issue by 13033266796** [cqmoe/python-aiocqhttp#29]
登录多个酷q，上报到同一个CQHTTP（）服务时，get_login_info()获取登录号信息只能获取到一个。如何才能获取到多个呢？

**Comment by ExerciseBook** [comment]
手操 cqhttp api 将请求发送到不同的 cqhttp 插件上？（我只是猜的）

**Comment by 13033266796** [comment]
可是CQHTTP()服务实例化的时候不是只能指定一个api_root吗？

**Comment by stdrc** [comment]
用反向 websocket，然后通过 `self_id` 参数指定

**Comment by ExerciseBook** [comment]
![image](https://user-images.githubusercontent.com/6327311/76482171-5dabfa80-644e-11ea-99e5-d25051aa98c0.png)
我这个的理解是使用 cqhttp 的裸 api 来实现。 import Request 。可能会很蠢。😂
具体还是挺 RC 大大的说法吧。

**Comment by 13033266796** [comment]
用反向 websocket，然后通过 self_id 参数指定，是指定QQ发送消息，这个是没问题的。但是我是想在CQHTTP()服务中获取到所有酷q客户端的登录号信息。

**Comment by stdrc** [comment]
> 但是我是想在CQHTTP()服务中获取到所有酷q客户端的登录号信息。

`get_login_info(self_id=12345678)` 同样可以

**Comment by stdrc** [comment]
我懂了，你想获取所有，那可能需要访问 aiocqhttp 内部数据了，看 [这个](https://github.com/cqmoe/python-aiocqhttp/blob/master/aiocqhttp/__init__.py#L143) 属性

**Comment by 13033266796** [comment]
可是我就是想获取qq号😂

**Comment by 13033266796** [comment]
> 我懂了，你想获取所有，那可能需要访问 aiocqhttp 内部数据了，看 [这个](https://github.com/cqmoe/python-aiocqhttp/blob/master/aiocqhttp/__init__.py#L143) 属性

我看看

**Comment by 13033266796** [comment]
bot._wsr_api_clients可以获取到，解决了。感谢您的帮助

**Comment by stdrc** [comment]
客气了
