### ISSUE TITLE
 result = await self.handle_user_exception(error)

### ISSUE THREAD

**Issue by Stone-wh** [cqmoe/python-aiocqhttp#30]
![image](https://user-images.githubusercontent.com/21095779/76623024-9a224800-656d-11ea-8222-075f28154a87.png)
突然之间报这个错误，大佬给看看
![image](https://user-images.githubusercontent.com/21095779/76623091-bcb46100-656d-11ea-8c70-a2a37c80dbec.png)

**Comment by stdrc** [comment]
首先你用的版本太老了，建议升级，其次你的这个报错是你自己代码的报错，建议自行排查
