### ISSUE TITLE
（提需求）支持以官方webhook方式发送消息

### ISSUE THREAD

**Issue by yuudi** [cqmoe/python-aiocqhttp#31]
发送消息增加一个参数，可以通过官方webhook通道发送消息，（最好能自动判断，如果消息中没有CQ码就用官方的发）

**Comment by stdrc** [comment]
没懂😂

**Comment by ExerciseBook** [comment]
![image](https://user-images.githubusercontent.com/6327311/78466511-6ed9e580-7734-11ea-9d18-f7d0a9315271.png)

应该是在 aiocqhttp 或者是 nonebot 中增加一个参数，把发送群消息的 api 转到这个 qqbot hook 中。

**Comment by yuudi** [comment]
我尝试了一下，发现官方webhook不太实用，对消息的过滤很严格，长一点的文本都发不出去。不太适合内置到框架中。
