### ISSUE TITLE
发送图片能否使用代理

### ISSUE THREAD

**Issue by Mauue** [cqmoe/python-aiocqhttp#36]
发送图片文档中好像只有使用图片url的方式，实际使用中有些图片无法直接通过url打开，需要使用代理之类的，但没有给出相应接口，有没有办法增加使用代理或者本地上传图片等方法来解决这一问题。

**Comment by ExerciseBook** [comment]
这也是酷Q本身不提供使用 url 发图片的原因。

酷Q推荐的操作方法是
1. 将图片自己放到 ```酷Q\data\image\``` 中，设文件名为 ```example.jpg```
2. 发送 ```[CQ:image,file=example.jpg]```

至于怎么放，方法也挺多的，ftp 啥的都可。

**Comment by stdrc** [comment]
用 CQHTTP 也可以的，系统环境变量设置 `HTTP_PROXY` 和 `HTTPS_PROXY`，然后重启（退出，再重开）酷Q即可
