### ISSUE TITLE
用反向ws连接，当aiocqhttp获取图片时收不到来自前端发来的消息。发送图片时，无法发送消息。

### ISSUE THREAD

**Issue by chenxuxin188** [cqmoe/python-aiocqhttp#38]
我的aiocqhttp用反向ws   通过universal连接。当收到指令时，会获取三张图片，然后发送出去。图片几MB这样，还要在本地通过pillow处理一下，然后再发出去。因为我离图片的服务器有点远，所以获取每张图片通常需要十几秒的时间。

当收到其他的消息时，会回复相同的消息。

我是通过requests来获取图片的：
```
print('获取图片')
r = requests.get(d['url'])
print('图片获取完成')
print('打开图片')
img = Image.open(BytesIO(r.content))
print('处理图片')
img.putpixel((0,0), (randrange(256), randrange(256), randrange(256)))
img.putpixel((img.size[0] - 1,0), (randrange(256), randrange(256), randrange(256)))
img.putpixel((0,img.size[1] - 1), (randrange(256), randrange(256), randrange(256)))
img.putpixel((img.size[0]- 2,img.size[1]- 2), (randrange(256), randrange(256), randrange(256)))
buffered = BytesIO()
img.save(buffered, format='PNG')
base = base64.b64encode(buffered.getvalue())
print('图片处理完成')
print('正在发送图片')
await bot.send(event, CQparse.img64(str(base.decode('utf-8'))))
print('图片发送完成')
```

然后我也把收到的消息在terminal里打印了出来，结果：
![QQ截图20200817014049](https://user-images.githubusercontent.com/30059986/90338719-ba799580-e02a-11ea-9bc6-8a8f2fa2d922.png)

就像这样，感觉消息就像是被阻塞住了一样，在获取完了图片之后一股脑地全都收到了。前端的日志显示的是消息全都正常发到了aiocqhttp这边，但是到最后才一股脑地收到。期间，在处理图片的那一点点时间里，会放出来几条消息。mirai和aiocqhttp都是在本机上运行的，所以两者之间通信应该不存在问题。

**Comment by mnixry** [comment]
很明显，PIL处理图片和requests进行网络请求是同步的IO操作
看起来你正在尝试在异步函数中调用同步函数，这样势必会造成IO阻塞
你似乎可以尝试使用线程池（aiocqhttp的on_message也是通过线程池支持同步函数的）

@on_message
def func

类似这样

**Comment by chenxuxin188** [comment]
> 很明显，PIL处理图片和requests进行网络请求是同步的IO操作
> 看起来你正在尝试在异步函数中调用同步函数，这样势必会造成IO阻塞
> 你似乎可以尝试使用线程池（aiocqhttp的on_message也是通过线程池支持同步函数的）
> 
> @on_message
> def func
> 
> 类似这样

处理图片的过程中是能正常收发消息的，只有在用request来获取图片的时候，没办法接受来自前端的消息，以及在用bot.send()的时候，没办法向前端发送消息。比如在发送图片的时候，aiocqhttp这边是能够看到发来的消息的。

**Comment by mnixry** [comment]
> 处理图片的过程中是能正常收发消息的，只有在用request来获取图片的时候，没办法接受来自前端的消息，以及在用bot.send()的时候，没办法向前端发送消息。比如在发送图片的时候，aiocqhttp这边是能够看到发来的消息的。

有可能是因为图片处理的速度快导致阻塞时间有限，所以表现在阻塞requests上？
你可以尝试用httpx代替requests来进行异步的HTTP请求，并且尝试增加异步或者同步的sleep来辅助调试

**Comment by chenxuxin188** [comment]
> > 处理图片的过程中是能正常收发消息的，只有在用request来获取图片的时候，没办法接受来自前端的消息，以及在用bot.send()的时候，没办法向前端发送消息。比如在发送图片的时候，aiocqhttp这边是能够看到发来的消息的。
> 
> 有可能是因为图片处理的速度快导致阻塞时间有限，所以表现在阻塞requests上？
> 你可以尝试用httpx代替requests来进行异步的HTTP请求，并且尝试增加异步或者同步的sleep来辅助调试

感谢大佬，试了一下异步sleep可以正常收发同步不行。换了httpx获取图片的时候能正常收发了。就是bot.send()发送大图片的时候还是不行。这个可能是mirai go的问题我到那边开个issue吧。。

**Comment by mnixry** [comment]
没有什么其他问题的话就先close了
还有问题可以随时reopen
