### ISSUE TITLE
能否定时发送消息

### ISSUE THREAD

**Issue by njzjz** [cqmoe/python-aiocqhttp#4]
能否定时发送消息，而非一定要处理事件

**Comment by stdrc** [comment]
HTTP API 本身就是专门用作在酷 Q 之上做转发事件为 HTTP 的，定时发送消息的话，你需要自行在自己的后端代码中写

**Comment by stdrc** [comment]
插件本身是没有业务逻辑的

**Comment by stdrc** [comment]
啊不好意思，我刚发现这里是 python-aiocqhttp，我以为我在回 HTTP API。

python-aiocqhttp 的话，你可以搭配使用 APScheduler，不用处理事件的，不需要使用 `@on_message` 来注册事件处理函数，只要运行了 `bot.run` 就行。

**Comment by ilihu** [comment]
如果是个异步的方法，用APScheduler怎么调啊？
eg:
``` python
async def send():
    return await send_group_msg()
```
这个 send 怎么用 APScheduler 每天定时调用一次

**Comment by stdrc** [comment]
> 如果是个异步的方法，用APScheduler怎么调啊？ eg:
> 
> ```python
> async def send():
>     return await send_group_msg()
> ```
> 
> 这个 send 怎么用 APScheduler 每天定时调用一次

APScheduler 有个 `AsyncIOScheduler`
