### ISSUE TITLE
反向WS的API接口发送后续请求有长时间延迟或直接超时

### ISSUE THREAD

**Issue by wfjsw** [cqmoe/python-aiocqhttp#40]
Related to: Mrs4s/go-cqhttp#147

通过反向WS使用API。除第一个请求准时发出外，后续请求均花费数分钟时间方能达到服务器。经常在等待回应超时后仍未发出。对所有API接口均有影响。

一开始以为是go-cqhttp的问题，后来给它开了好多刀之后问题仍然没解决，用wscat测试了一下发现go-cqhttp有及时回复API请求，所以问题应该出在aiocqhttp的某个地方，但并没有找到根源。

**Comment by stdrc** [comment]
go-cqhttp 那边确定回复的 `echo` 字段和发过去的一样吗

**Comment by wfjsw** [comment]
确定，内容和类型都一样

**Comment by cleoold** [comment]
Closed due to inactivity.
