### ISSUE TITLE
aiocqhttp1.3.0 + go-cqhttp v1.0.0-beta2 撤回消息失败并报错

### ISSUE THREAD

**Issue by zht163** [cqmoe/python-aiocqhttp#47]
我自己的问题，打扰了

**Comment by cleoold** [comment]
```
print(context)
```
的輸出是什麼?

**Comment by zht163** [comment]
是一个字典

**Comment by zht163** [comment]
这个message_id有时是正的有时是负的
我以为是bug了，所以直接把负的message_id转正数给使用了，所以报错

**Comment by zht163** [comment]
我不是把issu内容删了吗，你咋都给回复出来了，太丢人了

**Comment by zht163** [comment]
message_id需要这样匹配，这样正负message_id都能匹配到

message_id = int(re.findall(r'id=\S\d+', data)[0].split('=')[1])
