### ISSUE TITLE
Message及MessageSegment类使用 += 运算报错

### ISSUE THREAD

**Issue by freesrz93** [cqmoe/python-aiocqhttp#48]
**问题描述**
在开发过程中，负责处理消息并生成消息链的代码报错。经查证问题在于赋值语句中使用了 += 而非 +

**相关代码**
以下并非原始项目代码，仅为指出问题
```python
from aiocqhttp.message import MessageSegment, Message

msg1 = MessageSegment.image('https://i2.hdslb.com/bfs/face/88f2aa7e2e2.jpg')
msg2 = MessageSegment.text('text')
msg3 = MessageSegment.text('1234')
msg = msg1 + msg2
msg += msg3
print(list(msg))
```
预期输出
```python
[{'type': 'image', 'data': {'file': 'https://i2.hdslb.com/bfs/face/88f2aa7e2e2.jpg'}}, {'type': 'text', 'data': {'text': 'text1234'}}]
```
实际输出
```python
[{'type': 'image', 'data': {'file': 'https://i2.hdslb.com/bfs/face/88f2aa7e2e2.jpg'}}, {'type': 'text', 'data': {'text': 'text'}}, 'type', 'data']
```

**期望的行为**
尽管这不算bug，但希望能在文档中指出以供参考，或者重写Message及MessageSegment类的 __iadd__ 方法以支持用 += 操作消息链

**运行环境**
 - 操作系统：Windows10
 - aiocqhttp 版本：1.3.0
 - Python 版本：3.9.2

**Comment by stdrc** [comment]
这应该算 bug，之后修一下

**Comment by cleoold** [comment]
`Message` 和 `Message{|Segment}` 相加后得到的是 `Message`，所以使用 `+=` 比較合法.

`MessageSegment` 相加后得到的是 `Message`，類型變了，所以我打算禁止 `+=`.

(啊啦這個繼承 list 和 dict 的 Message 真是個不好的設計呢)

**Comment by stdrc** [comment]
> (啊啦這個繼承 list 和 dict 的 Message 真是個不好的設計呢)

确实不太好，当初是为了方便，可以少实现一些转换和各种魔术方法
