### ISSUE TITLE
'ActionFailed' object has no attribute 'retcode'

### ISSUE THREAD

**Issue by Ice9Coffee** [cqmoe/python-aiocqhttp#53]
**问题描述**
'ActionFailed' object has no attribute 'retcode'

**复现方法**
``` python
try:
    # something
except ActionFailed as e:
    logger.error(f'retcode={e.retcode}')
```

**期望的行为**
见文档
```python
    """
    OneBot 已收到 API 请求，但执行失败。

    ```py
    except ActionFailed as e:
        if e.retcode > 0:
            pass  # error code returned by CQHTTP
        elif e.retcode < 0:
            pass  # error code returned by CoolQ
    ```
    """
```

**运行环境**
 - 操作系统：Debian 10
 - aiocqhttp 版本：1.4.0
 - Python 版本：3.8

**Comment by Ice9Coffee** [comment]
或许1.4.0的实现不再需要显式指定retcode，直接调用__str__也能达到同样的目的。
目前的文档与新版实现有冲突，更新文档 or 代码做向下兼容，我觉得都可以。

**Comment by cleoold** [comment]
you can create a pr to remove the docstring

**Comment by Ice9Coffee** [comment]
> you can create a pr to remove the docstring

这段docstring存在蛮久了，而且在aiocqhttp的文档中也有，直接删掉对基于aiocqhttp<=1.3.0开发机器人的开发者是不负责任的行为。
向前兼容 或 提示开发者有不兼容的更改 才是更合理的做法吧。

**Comment by stdrc** [comment]
minor 版本号更新本来就不应该有不兼容的更改，这个当时 pr 合并得草率了（

**Comment by cleoold** [comment]
> 
> 
> > you can create a pr to remove the docstring
> 
> 这段docstring存在蛮久了，而且在aiocqhttp的文档中也有，直接删掉对基于aiocqhttp<=1.3.0开发机器人的开发者是不负责任的行为。
> 向前兼容 或 提示开发者有不兼容的更改 才是更合理的做法吧。

這次修改在 changelog 中提到了。即使是文檔還提到她只能代表文檔過期了。實際表現以 changelog 中提到的修改為准。

**Comment by stdrc** [comment]
> 這次修改在 changelog 中提到了。

更新日志只说了“调整 ActionFailed 错误信息格式”，并没有说到不兼容

**Comment by stdrc** [comment]
Fixed by #55
