### ISSUE TITLE
1.4.2版本有cq码匹配失败了

### ISSUE THREAD

**Issue by LHXnois** [cqmoe/python-aiocqhttp#60]
**问题描述**
1.4.2版本有cq码匹配失败了
匹配失败的cq码 （是闪照的cq码）
`[CQ:image,file=b28c0934872270182e030bd9ba972afb.image,url=,type=flash,subType=0]`
降级到1.4.1可以正常解析

**复现方法**
使用go-cqhttp-beat7作为协议端，aiocqhttp使用1.4.2版本，发送一张闪照
会被解析为
`&#91;CQ:image,file=b28c0934872270182e030bd9ba972afb.image,url=,type=flash,subType=0&#93;`

**期望的行为**
成功解析为图片cq码

**日志信息**
请附上 aiocqhttp 和 OneBot（CQHTTP）实现的运行日志（可截图或直接贴文本）。
go-cqhttp-beat7截图
![image](https://user-images.githubusercontent.com/43800204/134782323-300a8188-139c-4db9-970b-4d1546500d18.png)

hoshino（nonebot）截图
![image](https://user-images.githubusercontent.com/43800204/134781953-3b288a64-0771-46c9-9035-38bc6e6ed42d.png)

**相关代码**
```python
# 请在这里贴上你认为相关的代码
```

**运行环境**
 - 操作系统：windows
 - OneBot（CQHTTP）实现及版本：go-cqhttp-beat7
 - aiocqhttp 版本：1.4.2
 - Python 版本：3.8.3

**Comment by cleoold** [comment]
@mnixry is this related to your changes https://github.com/nonebot/aiocqhttp/pull/58

**Comment by mnixry** [comment]
请尝试在gocq中将上报消息格式设置为array，应该能暂时解决该问题

@cleoold 根据onebot标准，cq码的param不应该为空值，所以这应该属于上游实现的问题。我已向gocq开发者反馈此问题

**Comment by LHXnois** [comment]
经测试，改为array格式上传确实可以正常解析了
![image](https://user-images.githubusercontent.com/43800204/134812098-95ea2902-ac55-4691-ab7c-317a036d5f2a.png)

**Comment by Ink-33** [comment]
由于闪照没办法提供永久链接，所以gocq这边没有提供闪照的url。
目前解决方案需要进行讨论

**Comment by stdrc** [comment]
> @cleoold 根据onebot标准，cq码的param不应该为空值，所以这应该属于上游实现的问题。我已向gocq开发者反馈此问题

我重新看了下 OneBot 11，才意识到，标准没有规定 CQ 码参数值不能为空，表述是这样的：

> CQ 码中不应有多余的空格，例如不应该使用 [CQ:face, id=178]。
>
> CQ 码的参数值可以包含空格、换行、除 `[],&` 之外的特殊符号等。在解析时，应直接取 `[CQ:` 后、第一个 `,` 或 `]` 前的部分为功能名，第一个 `,` 之后到 `]` 之间的部分为参数，按 `,` 分割后，每个部分第一个 `=` 前的内容为参数名，之后的部分为参数值。例如 `[CQ:share,title=标题中有=等号,url=http://baidu.com]` 中，功能名为 `share`，`title` 参数值为 `标题中有=等号`，`url` 参数值为 `http://baidu.com`。

“每个部分第一个 `=` 前的内容为参数名，之后的部分为参数值”，这里“之后的部分”没说不能为空。
