### ISSUE TITLE
Update Quart to 0.16.0

### ISSUE THREAD

**Issue by GirlKiller512** [cqmoe/python-aiocqhttp#61]
**问题描述**
Quart 的作者在昨天才发布了第一个支持 Python 3.10 的版本
aiocqhttp (NoneBot) 可以在 Python 3.10 上安装，但是 Quart 被限制在了 0.14.1 版本
是不是要升级一下依赖了
https://github.com/pgjones/quart/blob/0.16.0/CHANGELOG.rst
~~（直接把~~ `<0.15` ~~去掉应该是可以的吧）~~

**复现方法**
无

**期望的行为**
Quart 升级到 0.16.0 版本

**日志信息**
无

**相关代码**
无

**运行环境**
 - 操作系统：Ubuntu 20.04.3
 - OneBot（CQHTTP）实现及版本：无
 - aiocqhttp 版本：1.4.2
 - Python 版本：3.10.0

**Comment by stdrc** [comment]
可以，你来发个 pr？不要直接去掉 `<0.15`，改成限制在目前最新版就行，不然以后有出问题的可能（当时加上限制好像就是因为出过问题）
