### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by w0330t** [cqmoe/python-aiocqhttp#8]
我使用说明里的demo代码，使用反向ws模式，我吧代码复制到一个py文件里运行，然后就没有然后了，我估计连API都没通……
coolq配置在一个docker里面，配置内容如下
```
serve_data_files = yes
ws_reverse_url = 192.168.10.201
use_ws_reverse = yes
```
IP地址我确认无误，

然后我想问一下如何发送消息，
我知道api是bot.send_private_msg(user_id=123456, message='hello')
是否直接在bot.run之后加入这一行就可以了？

**Comment by stdrc** [comment]
aiocqhttp 不支持 `ws_reverse_url`，需要分开 `ws_reverse_url_api` 和 `ws_reverse_url_event`，并且，格式是 `ws://192.168.10.201:端口/ws/api/` 这样

**Comment by stdrc** [comment]
> 是否直接在bot.run之后加入这一行就可以了？

不是，`bot.run` 会卡死的（进入事件循环），你需要在其它地方调用 `bot.send_private_msg`，比如 `on_message` 回调，如果你要定时发，可以用 APScheduler 的 AsyncIOScheduler

**Comment by w0330t** [comment]
大概懂了，然后闹了点笑话，然而不太明白async，我去研究研究。

**Comment by stdrc** [comment]
没事，加油，asyncio 是个好东西（

**Comment by w0330t** [comment]
再问一下……
